dependencies:
  - name: spring-sample-chart
    version: 1.0.0
    repository: "file://../spring-sample-chart"
    alias: a
dependencies:
  - name: spring-sample-chart
    version: 1.1.0
    repository: "file://../spring-sample-chart"
    alias: b