apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}-{{ .Chart.Version }}
spec:
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds}}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
        version: {{ .Chart.Version }}
    spec:
      containers:
        - name: {{ .Values.global.image.name }}
          image: "{{ .Values.global.image.repository }}/{{ .Values.global.image.name }}:{{ .Values.global.image.tag }}-{{ .Chart.Version }}"
          imagePullPolicy: {{ .Values.global.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.deployment.port }}
