apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    service: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.internalPort }}
      nodePort: {{ .Values.service.externalPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    app: {{ .Chart.Name }}
