replicaCount: 1
minReadySeconds: 1

service:
  name: spring-service
  type: NodePort
  externalPort: 30080
  internalPort: 8080  
deployment:
  name: spring-deployment
pod:
  name: spring-container

global:
  image:
    name: spring-sample
    repository: hub.docker.com/cloud-agility/
    tag: local
    pullPolicy: IfNotPresent