replicaCount: 1
minReadySeconds: 1

deployment:
  name: spring-deployment
  port: 8080

global:
  image:
    name: spring-sample
    repository: hub.docker.com/cloud-agility/
    tag: local
    pullPolicy: IfNotPresent
