apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    service: identity
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30002
    protocol: TCP
  selector:
    application: spring-sample