apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: spring-sample-default
spec:
  destination:
    name: {{ .Values.service.name }}
  precedence: 1
  route:
  - labels:
      version: "1.0.0"
    weight: 50
  - labels:
      version: "1.1.0"
    weight: 50
