apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: spring-sample-default
spec:
  destination:
    name: {{ .Values.service.name }}
  precedence: 1
  route:
    {{- range .Values.route }}
      {{ . }}
    {{- end }}
